name: vam
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  http: ^0.13.3
  carousel_pro: ^1.0.0
  shared_preferences: ^2.0.5
  simple_animations: ^1.3.3
  share: ^0.6.5
  social_share: ^2.0.5
  webview_flutter: ^2.0.6
  url_launcher: ^6.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/images/crazelogo.png"
  android: true
  ios: true
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/login.jpg
    - assets/images/logins.png
    - assets/images/signup.png
    - assets/images/otppic.jpg
    - assets/images/login.svg
    - assets/images/chaticon.svg
    - assets/images/facebook_logo.svg
    - assets/images/google_plus.svg
    - assets/images/ordericon.svg
    - assets/images/profile_icon.svg
    - assets/images/otppic.svg
    - assets/images/tick.gif
    - assets/images/setpass.jpg
    - assets/images/add.svg
    - assets/images/globe.svg
    - assets/images/graph.svg
    - assets/images/tag.svg
    - assets/images/add.svg
    - assets/images/refer.png
    - assets/images/mapp.png
    - assets/images/giftbox.svg
    - assets/images/box.svg
    - assets/images/error.gif
    - assets/images/whatsapp.svg
    - assets/images/translate.svg
    - assets/images/information.svg
    - assets/images/placeholder.svg
    - assets/images/shopping-cart.svg
    - assets/images/subscription.svg
    - assets/images/rupee-indian.svg
    - assets/images/right-arrow.svg
    - assets/images/location.svg
    - assets/images/pickup.svg
    - assets/images/faq.svg
    - assets/images/history.svg
    - assets/images/privacy-policy(1).svg
    - assets/images/terms-and-conditions.svg
    - assets/images/subscribe.jpg
    - assets/images/error.svg
    - assets/images/wallet.svg
    - assets/images/money.svg
    - assets/images/mobile-payment.svg
    - assets/images/error.png
    - assets/images/store.svg
    - assets/images/point.svg
    - assets/images/ic_done.png
    - assets/images/mapp.jpg
    - assets/images/wrong.gif
    - assets/images/crazelogo.png
    - assets/images/crypto.png
    - assets/images/vam1.jpeg
    - assets/images/vam2.jpeg
    - assets/images/vam3.jpeg
    - assets/images/vam4.jpeg
    - assets/images/vam5.jpeg
    - assets/images/vam6.jpeg
    - assets/images/vam7.jpeg
    - assets/images/vam8.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: RobotoBold
      fonts:
        # - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        # - asset: assets/fonts/Roboto-BoldItalic.ttf
        # - asset: assets/fonts/Roboto-Italic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
